{% set name = "dufte" %}
{% set version = "0.2.28" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dufte-{{ version }}.tar.gz
  sha256: f3deb8fecd63b81cf3d34f6d05236806aa2b9a499399563fe42f9a074d7a0db2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base
    - numpy
    - python >=3.6

test:
  imports:
    - dufte
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nschloe/dufte
  summary: Clean matplotlib plots
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - izahn
