{% set name = "dufte" %}
{% set version = "0.2.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dufte-{{ version }}.tar.gz
  sha256: 9c2d082595a1ce653b990c1cc6c82306eeab3d6513faa61a54c180543ce08633

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base
    - numpy
    - python >=3.6

test:
  imports:
    - dufte
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nschloe/dufte
  summary: Clean matplotlib plots
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - izahn
